
 //PROJECT
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA"; 
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
export const ADD_USER_PROJECT_API = 'ADD_USER_PROJECT_API';
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA';
export const GET_USER_API = 'GET_USER_API'; //LIST OF ALL USER OF ALL PROJECTS
export const GET_ALL_PROJECT_LIST = 'GET_ALL_PROJECT_LIST'; //PROJECT LIST DROPDOWN FOR SELECTING 
export const GET_ALL_PROJECT_DROPDOWN_LIST = 'GET_ALL_PROJECT_DROPDOWN_LIST'; //SAVE PROJECT LIST IN REDUCER 
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const PUT_PROJECT_DETAIL = 'PUT_PROJECT_DETAIL';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';

//PRIORITY
export const GET_ALL_PRIORITY_LIST_SAGA = 'GET_ALL_PRIORITY_LIST_SAGA';
export const GET_ALL_PRIORITY_DROPDOWN = 'GET_ALL_PRIORITY_DROPDOWN'

//TASK TYPE 
export const GET_ALL_TYPE_TASK_SAGA = 'GET_ALL_TYPE_TASK_SAGA'
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';

//DRAWER : FORM + SUBMIT BUTON
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const OPEN_FORM_EDIT_PROJECT = 'OPEN_FORM_EDIT_PROJECT';
export const EDIT_PROJECT_SAGA_DRAWER = 'EDIT_PROJECT_SAGA_DRAWER';

export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK';
export const SET_SUBMIT_EDIT_PROJECT = 'SET_SUBMIT_EDIT_PROJECT';
export const SET_SUBMIT_CREATE_PROJECT = 'SET_SUBMIT_CREATE_PROJECT';
export const SET_SUBMIT_EDIT_USER_INFO = 'SET_SUBMIT_EDIT_USER_INFO'; 
export const SET_SUBMIT_CREATE_A_USER = 'SET_SUBMIT_CREATE_A_USER'; 


//TASK 
export const GET_TASK_DETAIL_REDUCER = 'GET_TASK_DETAIL_REDUCER'; 
export const UPDATE_TASK_SAGA  = "UPDATE_TASK_SAGA";
export const HANDLE_CHANGE_POST_API  = "HANDLE_CHANGE_POST_API";
export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN';
export const CHANGE_TASK_MODAL  = "CHANGE_TASK_MODAL"; 

//STATUS 
export const UPDATE_TASK_STATUS_SAGA = 'UPDATE_TASK_STATUS_SAGA';
export const GET_ALL_STATUS = 'GET_ALL_STATUS';
export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';
//USERS 
export const GET_USER_SEARCH = 'GET_USER_SEARCH'; //SEARCH USER BY KEYWORD
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID'; 
export const GET_ALL_USER_REDUCER = 'GET_ALL_USER_REDUCER'; 
export const GET_ALL_USERS_SAGA = 'GET_ALL_USERS_SAGA';  //ALL USERS OF CERTAIN TASK
export const DELETE_USER_FROM_LIST_SAGA = 'DELETE_USER_FROM_LIST_SAGA'; 
export const EDIT_USER_INFO_SAGA = 'EDIT_USER_INFO_SAGA'
export const USER_SIGN_UP_SAGA = 'USER_SIGN_UP_SAGA';
export const USER_EDIT_INFO_REDUCER = 'USER_EDIT_INFO_REDUCER'; 
export const OPEN_FORM_EDIT_USER_INFO = 'OPEN_FORM_EDIT_USER_INFO'; 
export const OPEN_FORM_CREATE_USER = 'OPEN_FORM_CREATE_USER'
export const CREATE_A_USER = 'CREATE_A_USER'; 
export const USER_SIGNIN_API = "USER_SIGNIN_API"; 
export const USLOGIN = "USLOGIN";
export const DELETE_USER_PROJECT_API = 'DELETE_USER_PROJECT_API';
export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA'

export const CHANGE_ASSINGEES  = "CHANGE_ASSINGEES"; //ASSIGN USER TO CERTAIN TASK 

//comment 
export const GET_ALL_COMMENTS_REDUCER = 'GET_ALL_COMMENTS_REDUCER'; 
export const GET_ALL_COMMENTS_SAGA = 'GET_ALL_COMMENTS_SAGA';
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const INSERT_A_COMMENT_SAGA = 'INSERT_A_COMMENT_SAGA';
export const CANCEL_EDIT_COMMENT = 'CANCEL_EDIT_COMMENT';
export const EDIT_A_COMMENT_SAGA = 'EDIT_A_COMMENT_SAGA'; 
export const DELETE_A_COMMENT_SAGA = 'DELETE_A_COMMENT_SAGA'


